service: employer
frameworkVersion: '2'
disabledDeprecations: 
  - '*'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    EMPLOYER_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
plugins:
  - serverless-offline
  - serverless-dynamodb-local
package:
  individually: true

resources:
  Resources:
    EmployersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.EMPLOYER_TABLE}

functions:
  employerSubmission:
    handler: api/employer.submit
    memorySize: 128
    description: Submit employer information and starts interview process.
    events:
      - http: 
          path: employers
          method: post
  listEmployers:
    handler: api/employer.list
    memorySize: 128
    description: List all employers
    events:
      - http: 
          path: employers
          method: get 
  updateEmployer:
    handler: api/employer.update
    memorySize: 128
    description: Update employer
    events:
      - http: 
          path: employers
          method: patch
  removeEmployer:
    handler: api/employer.remove
    memorySize: 128
    description: Remove employer
    events:
      - http: 
          path: employers
          method: delete
          request:
            parameters:
              querystrings:
                id: true   
